
version: '2'

services:
  faces-book:
    user: root
    image: ${FACES_BOOK_IMAGE}
    container_name: ${FACES_BOOK_CONTAINER}
    tmpfs: /tmp
    build:
      context: app
      args:
        - PORT=${FACES_BOOK_PORT}
    ports:
      - ${FACES_BOOK_PORT}:${FACES_BOOK_PORT}
